# Generated by Django 5.0 on 2024-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_table',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
