# Generated by Django 5.0 on 2024-03-11 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_enquiry_table_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='date_field',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
